// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SemanticKeys tool.
//     Runtime changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace sk
{
    using SemanticKeys;

    public static class Modifiers
    {
        public static readonly SemanticKey Static = new SemanticKey("ca18840d-58a5-4dc3-9b6a-c294c86a3520", "Static", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Linear = new SemanticKey("9bdcc19d-af29-4c54-944f-8a594af59ecc", "Linear", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Polynomial = new SemanticKey("ac52fe5e-93f6-4d4c-9b1b-3ab5acd48b34", "Polynomial", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Clamp = new SemanticKey("52475db6-7319-43ad-91b5-8580761e8665", "Clamp", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Min = new SemanticKey("ab9c9445-86eb-416c-8c98-500d3a6b4f01", "Min", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Max = new SemanticKey("6a700966-1f76-4ab0-a127-6b1c9f01c934", "Max", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Floor = new SemanticKey("4bc21179-f06e-4d34-9739-6762f55becd3", "Floor", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Step = new SemanticKey("d09224bf-32e7-47f1-b9f6-360db9c08808", "Step", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Ratio = new SemanticKey("ae2b187e-330c-4b0c-9144-f121fc5232e9", "Ratio", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey Exponential = new SemanticKey("e57bd643-b170-4e91-83b3-e27216439255", "Exponential", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey DiminishingReturns = new SemanticKey("30b90d2e-eca3-4441-8fd9-bc4709e0cdc5", "DiminishingReturns", "3401e59b-f306-41ed-80e7-428c88bfbda0");
        public static readonly SemanticKey ScaledTriangular = new SemanticKey("e190125a-ddb8-4e1e-a31a-94205da9253a", "ScaledTriangular", "3401e59b-f306-41ed-80e7-428c88bfbda0");
    }
}
